### ISSUE TITLE
make mobile-friendly

### ISSUE THREAD

**Issue by gbinal** [benbalter/is-pennsylvania-avenue-open#1]

**Comment by jpyuda** [comment]
I was just coming here to pull request and there is no code!

**Comment by gbinal** [comment]
Refresh.  :)

**Comment by benbalter** [comment]
> and there is no code!

Must have visited between repository creation and first push. There's lots of code now!

**Comment by benbalter** [comment]
Fixed via https://github.com/benbalter/is-pennsylvania-avenue-open/commit/818dcee59470704e6b86961f756e0b6844055f74.

![screen shot 2015-02-04 at 3 07 40 pm](https://cloud.githubusercontent.com/assets/282759/6048626/9bfe8d8e-ac7f-11e4-949c-d63a30e5ed76.png)
